spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_db
    username: postgres
    password: password
kafka:
  bootstrap-servers: localhost:9092
  topics:
    trip-events: trip-events
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/